name: bi
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip:

# Manually install the following
# Pillow
# tqdm
# scikit-learn==1.5.2
# numpy==2.0.2
# torch==2.5.0
# matplotlib
# networkx
# cvxpy
# torchvision
# tensorboard
