name: bi
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip:
        # Pillow == 8.1.2
        # tqdm
        # scikit-learn == 0.21.3
        # numpy == 1.19.0
        # torch == 1.2.0
        # matplotlib == 3.1.1
        # networkx == 2.5.1
        # cvxpy
        # torchvision
        # tensorboard
      # - Pillow==8.1.2
      # - tqdm
      # - scikit-learn==0.21.3
      # # - numpy==1.19.0
      # - torch==1.2.0
      # - matplotlib==3.1.1
      # - networkx==2.5.1
      # - cvxpy
      # - torchvision
      # - tensorboard

# Pillow
# tqdm
# scikit-learn==1.5.2
# numpy==2.0.2
# torch==2.5.0
# matplotlib
# networkx
# cvxpy
# torchvision
# tensorboard